CREATE TABLE Branch (branchname VARCHAR2(30),branchcity VARCHAR2(20) NOT NULL,asset NUMBER CHECK (asset > 0) NOT NULL);

CREATE TABLE Customer (custname VARCHAR2(30),custstreet VARCHAR2(50),custcity VARCHAR2(20) NOT NULL);

CREATE TABLE Account (accnum NUMBER PRIMARY KEY,branchname VARCHAR2(30),balance NUMBER CHECK (balance > 500));

CREATE TABLE Loan (loanno NUMBER PRIMARY KEY,branchname VARCHAR2(30),amount NUMBER CHECK (amount > 0));

CREATE TABLE Borrower (custname VARCHAR2(30),loanno NUMBER,PRIMARY KEY (custname, loanno),FOREIGN KEY (custname) REFERENCES Customer(custname),FOREIGN KEY (loanno) REFERENCES Loan(loanno));

CREATE TABLE Depositor (custname VARCHAR2(30),accnum NUMBER,PRIMARY KEY (custname, accnum),FOREIGN KEY (custname) REFERENCES Customer(custname),FOREIGN KEY (accnum) REFERENCES Account(accnum));

ALTER TABLE Customer MODIFY custstreet VARCHAR2(50) NOT NULL;

ALTER TABLE Customer ADD phoneNo VARCHAR2(20);

ALTER TABLE Customer ADD custage NUMBER;

ALTER TABLE Customer ADD CONSTRAINT chk_custage CHECK (custage > 18);

ALTER TABLE Customer MODIFY phoneNo VARCHAR2(10);

ALTER TABLE Customer DROP COLUMN phoneNo;

ALTER TABLE Customer DROP CONSTRAINT chk_custage;

CREATE TABLE EMPLOYEE (Emp_no NUMBER PRIMARY KEY,E_name VARCHAR2(50),E_address VARCHAR2(100),E_ph_no VARCHAR2(20),Dept_no NUMBER,Dept_name VARCHAR2(50),Job_id VARCHAR2(20),Salary NUMBER(10,2));

ALTER TABLE EMPLOYEE ADD HIREDATE DATE;

ALTER TABLE EMPLOYEE MODIFY Job_id VARCHAR2(20);

ALTER TABLE EMPLOYEE RENAME COLUMN Emp_no TO E_no;

ALTER TABLE EMPLOYEE MODIFY Job_id VARCHAR2(30);

CREATE TABLE EMP (EMPNO NUMBER(6) PRIMARY KEY,ENAME VARCHAR2(20) NOT NULL,JOB VARCHAR2(10) NOT NULL,DEPTNO NUMBER(3),SAL NUMBER(7,2));

ALTER TABLE EMP ADD CONSTRAINT chk_empno CHECK (EMPNO > 100);

ALTER TABLE EMP ADD CONSTRAINT unq_deptno UNIQUE (DEPTNO);
